kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: ubuntu:focal-20210609
  environment:
    SCP_ID:
      from_secret: id
    SCP_PUB:
      from_secret: pub
  commands:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq build-essential git wget curl cmake libfreetype-dev libtbb-dev libfreeimage-dev libvtk6-dev flex bison rapidjson-dev tcl-dev tk-dev doxygen graphviz libxmu-dev libxi-dev swig pv
  - git fetch --tags
  - mkdir ~/.ssh
  - echo "$${SCP_ID}" | cat > ~/.ssh/id_rsa
  - echo "$${SCP_PUB}" | cat > ~/.ssh/id_rsa.pub
  - chmod go-rwx ~/.ssh -R
  - make build-baseimage
  - CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
  - BRANCH=""; if [ "$${CURRENT_BRANCH}" != "master" ]; then BRANCH="$${CURRENT_BRANCH}_"; fi
  - VERSION=$(git describe --tags)
  - echo "Uploading version $${VERSION}"
  - |
    GIT_TAG=$(git describe --tags --no-abbrev)
    curl --insecure -u droneio: --key ~/.ssh/id_rsa --pubkey ~/.ssh/id_rsa.pub -T bcad.AppDir.tar.gz sftp://10.218.35.100/srv/deb-repositories/archive/drone/bcad_base_image/$${BRANCH}bcad.AppDir-$${VERSION}.tar.gz
