kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: ubuntu:focal-20210609
  environment:
    SCP_USER:
      from_secret: scp_username
    SCP_PWD:
      from_secret: scp_pwd
  commands:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq build-essential git wget curl
  - git fetch --tags
  - mkdir ~/.ssh
  - echo ${id} | cat > ~/.ssh/id_rsa
  - echo ${pub} | cat > ~/.ssh/id_rsa.pub
  - chmod go-rwx ~/.ssh -R
  - mkdir bcad.AppDir; touch bcad.AppDir/empty; tar czf bcad.AppDir.tar.gz bcad.AppDir; #make build-baseimage
  - CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
  - BRANCH=""; if [ "${CURRENT_BRANCH}" != "master" ]; then BRANCH="${CURRENT_BRANCH}_"; fi
  - VERSION=$(git describe --tags)
  - echo "Uploading version ${VERSION}"
  - |
    GIT_TAG=$(git describe --tags --no-abbrev)
    curl -u droneio: --key ~/.ssh/id_rsa --pubkey ~/.ssh/id_rsa.pub -T bcad.AppDir.tar.gz sftp://10.218.35.100/srv/deb-repositories/archive/drone/bcad_base_image/${BRANCH}bcad.AppDir-${VERSION}.tar.gz
